apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-be-deployment
  labels:
    app: lms-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-be
  template:
    metadata:
      labels:
        app: lms-be
    spec:
      containers:
      - name: lms-be-cont
        image: prchekuri/lms-be
        ports:
          - containerPort: 4000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: be-db-secret
                key: DATABASE_URL
        command: ["sh", "-c", "node build/index.js || sleep 3600"]